server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.120.101:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.120.101:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
  service:
    v-group-mapping:
      seata-demo: SH
  #data-source-proxy-mode: XA
  data-source-proxy-mode: AT #需要全局锁的表  lock-table和 快照表   undo_log
  #config:
    #type: nacos
    #nacos:
      #server-addr: 127.0.0.1:8848
      #username: nacos
      #password: nacos
      #group: SEATA_GROUP
      #data-id: client.properties